#!/bin/bash

echo "Creating symlinks for dotfiles to $HOME"

# make backups of already existing dotfiles
for f in $(find dotfiles -type f); do
  FILE="${f#dotfiles/}"
  if [[ -f ~/$FILE ]]; then
    mkdir -p ~/.dotfiles.bak
    if [[ $(dirname $FILE) != "." ]]; then
      mkdir -p ~/.dotfiles.bak/$(dirname $FILE)
    fi
    cp ~/$FILE ~/.dotfiles.bak/$FILE
    echo "Made backup of $FILE in ~/.dotfiles.bak/"
  fi
done

# make parent directories
for f in $(find dotfiles/ -type d); do
  mkdir -p ~/${f#dotfiles/}
done

# Symlink all dotfiles
for f in $(find dotfiles -type f); do
  FILE="${f#dotfiles/}"
  ln -sf "$PWD/dotfiles/$FILE" "$HOME/$FILE"
done

# Source .zshrc to update env
# Ignore the errors generated by this source.
# They only appear during this process. They work properly on new shell startup.
echo "Linked dotfiles. Please restart your shell. "
